all: vectorlib.h vecadd.c vecangle.c dotProductVectors.c elementProductVectors.c vecnorm.c subtractVectors.c vectorMain.c
		gcc -o vectorMain vectorMain.c vecadd.c vecangle.c dotProductVectors.c elementProductVectors.c vecnorm.c subtractVectors.c -lm

clean:
		rm vectorMain 