all: vectorlib.h addVectors.c angleBetweenVectors.c dotProductVectors.c elementProductVectors.c vecnorm.c subtractVectors.c vectorMain.c
		gcc -o vectorMain vectorMain.c addVectors.c angleBetweenVectors.c dotProductVectors.c elementProductVectors.c vecnorm.c subtractVectors.c -lm

clean:
		rm vectorMain 